package DRRSApp;


/**
* DRRSApp/DRRS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DRRSidl.idl
* Tuesday, October 19, 2021 12:12:48 o'clock AM EDT
*/

public interface DRRS extends DRRSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DRRS
