package DRRSApp;


/**
* DRRSApp/DRRSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DRRSidl.idl
* Tuesday, October 19, 2021 12:12:48 o'clock AM EDT
*/

public interface DRRSOperations 
{
  String createRoom (String room_Number, String date, String beginTime, String endTime);
  String deleteRoom (String room_Number, String date, String[] listOfTimeSlotsIndexFromInputString);
  String bookRoom (String studentID, String campusName, String roomNumber, String date, int timeslot);
  boolean overLimit (String studentID);
  String[] getTimeSlots (String date, String room, String campus);
  String cancelBooking (String bookingID, String studentID);
  String changeReservation (String studentID, String bookingID, String newCampusName, String date, String newRoomNo, String newTimeSlot);
  void shutdown ();
} // interface DRRSOperations
