package DRRSApp;


/**
* DRRSApp/DRRSHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DRRSidl.idl
* Tuesday, October 19, 2021 12:12:48 o'clock AM EDT
*/

abstract public class DRRSHelper
{
  private static String  _id = "IDL:DRRSApp/DRRS:1.0";

  public static void insert (org.omg.CORBA.Any a, DRRSApp.DRRS that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DRRSApp.DRRS extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DRRSApp.DRRSHelper.id (), "DRRS");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DRRSApp.DRRS read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DRRSStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DRRSApp.DRRS value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DRRSApp.DRRS narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DRRSApp.DRRS)
      return (DRRSApp.DRRS)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DRRSApp._DRRSStub stub = new DRRSApp._DRRSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DRRSApp.DRRS unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DRRSApp.DRRS)
      return (DRRSApp.DRRS)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DRRSApp._DRRSStub stub = new DRRSApp._DRRSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
