package AuthenticationApp;


/**
* AuthenticationApp/AuthenticationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Authentication.idl
* Wednesday, October 13, 2021 10:02:53 o'clock PM EDT
*/

public interface AuthenticationOperations 
{
  String authorize (String id, boolean isAdmin);
  void shutdown ();
} // interface AuthenticationOperations
